config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users do
    collection do
      patch :bulk_update
      delete :bulk_delete
      delete :delete_selected
    end
  end
  

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    if params[:user][:password].present?
      super
    else
      # If the user does not want to change the password, remove the password attributes
      # to avoid validation errors
      resource.update_without_password(user_params)
      # Sign in the user because Devise doesn't handle sign in after update_without_password
      bypass_sign_in(resource, scope: resource_name)
      # Redirect to wherever you want
      redirect_to root_path, notice: "Account updated successfully."
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_unauthenticated_user
  #before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  
  def redirect_unauthenticated_user
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "You must be signed in to access this page."
    end
  end
  def bulk_update
  
    @selected_users=User.where(id:params.fetch(:user_ids,[]).compact)
    #binding.b
    if params[:commit]=="Block"
      @selected_users.update_all(status: :blocked)
      redirect_to users_path, notice: "User status updated successfully."
    elsif params[:commit]=="active"
      @selected_users.update_all(status: :active)
      redirect_to users_path, notice: "User status updated successfully."
    else
      redirect_to users_path, notice: "No user selected."
    end
  end

    

  #   @selected_users = User.where(id: params.fetch(:user_ids, []).compact)
  #   if params[:commit] == 'block'
  #     @selected_users.update_all(status: :blocked)
  #   elsif params[:commit] == 'unblock'
  #     # @selected_users.each { |u| u.active! }
  #     @selected_users.update_all(status: :active)
  #   end
  #   flash[:notice] = "#{@selected_users.count} users marked as #{params[:commit]}"
  #   redirect_to action: :index
  # end
  # def block_unblock
  #   user_id = params[:user_id]
  #   puts "..........................My Id............###############//////////////////"
  #   puts params[:user_id]
  #   status = params[:status]

  #   # Find the user by ID
  #   user = User.find(user_id)

  #   # Update the user's status
  #   user.update(status: status)

  #   # Redirect or render as needed
  #   redirect_to users_path, notice: "User status updated successfully."
  def bulk_delete
    @selected_users = User.where(id: params.fetch(:user_ids, []).compact)
    # puts "555555555555555555555555anything55555555555555555555555"
    # binding.b
    if @selected_users.empty?
      # Handle case where no users are selected
      flash[:alert] = "No users selected for deletion."
    else
      @selected_users.destroy_all
      flash[:notice] = "Selected users have been deleted successfully."
      
    end
  end 

  def delete_selected
    # Implement logic to delete selected users
  end
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>
  <div>
  <%= form.label :encrypted_password, style: "display: block" %>
  <%= form.text_field :Password %>
</div>
  <div>
<p>Something</p>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<head>
  <!-- Other head content -->

  <style>
    .checkbox-label {
      cursor: pointer;
    }

    /* Additional CSS styles */
    /* You can add more styles here */
  </style>

</head>


<tr>
<th scope="row"><%= check_box_tag "user_ids[]", user.id, nil, { multiple: true, form: :bulk_actions_form, data: { checkbox_select_all_target: "child", action: "change->checkbox-select-all#toggleParent"} } %>
 <%= check_box_tag "user_ids[]", user.id, nil, { multiple: true, form: :bulk_delete_form, data: { checkbox_select_all_target: "child01", action: "change->checkbox-select-all#toggleParent"} } %></th>
<td><%=user.name%></td>
<td><%=user.email%></td>
<td><%=user.last_sign_in_at%></td>
<td><%=user.status%></td>

</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Users</h1>



<%= form_with url: bulk_update_users_path, method: :patch, id: :bulk_actions_form do |form| %>
  <%= form.submit "active", class: "btn btn-light with-icon01" %>
  <%= form.submit "Block", class: "btn btn-light with-icon" %>
<% end %>
<%= form_with url: bulk_delete_users_path, method: :DELETE, id: :bulk_delete_form do |form| %>
  <%= form.submit "Delete", class: "btn btn-danger" %>
<% end %>
<div data-controller="checkbox-select-all">
<table class="table table-light table-striped table table-hover table table-bordered">
  <thead>
    <tr>
      <th scope="col"><%= check_box_tag "select all", nil, nil, { data: { checkbox_select_all_target: "parent", action: "change->checkbox-select-all#toggleChildren"} } %></th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Last Login</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
  
  </tbody>
</table>
</div>
<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>